# Copyright (c) 2024 Polytechnique Montreal
# Bitstream generation
# ---------------------------------------------------------------------
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK Enable [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 63.8 [current_design]
#set_property BITSTREAM.CONFIG.CONFIGRATE 85.0          [current_design]                 ;# Customer can try but may not be reliable over all conditions.
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN disable [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR Yes [current_design]
# ---------------------------------------------------------------------

# Don't time the GPIO reset signals
set_false_path -from [get_pins -hier *Not_Dual.gpio_Data_Out_reg*/C]

# 156.25MHz General purpose system clock
set_property PACKAGE_PIN BH6 [get_ports chipset_clk_osc_p]
set_property PACKAGE_PIN BJ6 [get_ports chipset_clk_osc_n]
set_property IOSTANDARD LVDS [get_ports chipset_clk*]

# Reset, connects SW1 push button On the top edge of the PCB Assembly, also connects to Satellite Controller
set_property PACKAGE_PIN L30 [get_ports resetn]
set_property IOSTANDARD LVCMOS18 [get_ports resetn]

# UART
set_property PACKAGE_PIN A28 [get_ports uart_rx]
set_property PACKAGE_PIN B33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS18 [get_ports uart_*]

# PCIe MGTY Interface
set_property PACKAGE_PIN BH26 [get_ports pcie_perstn]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_perstn]

set_property PACKAGE_PIN BC2 [get_ports {pci_express_x16_rxp[15]}]
set_property PACKAGE_PIN BC1 [get_ports {pci_express_x16_rxn[15]}]
set_property PACKAGE_PIN BC7 [get_ports {pci_express_x16_txp[15]}]
set_property PACKAGE_PIN BC6 [get_ports {pci_express_x16_txn[15]}]
set_property PACKAGE_PIN BB4 [get_ports {pci_express_x16_rxp[14]}]
set_property PACKAGE_PIN BB3 [get_ports {pci_express_x16_rxn[14]}]
set_property PACKAGE_PIN BC11 [get_ports {pci_express_x16_txp[14]}]
set_property PACKAGE_PIN BC10 [get_ports {pci_express_x16_txn[14]}]
set_property PACKAGE_PIN BA2 [get_ports {pci_express_x16_rxp[13]}]
set_property PACKAGE_PIN BA1 [get_ports {pci_express_x16_rxn[13]}]
set_property PACKAGE_PIN BB9 [get_ports {pci_express_x16_txp[13]}]
set_property PACKAGE_PIN BB8 [get_ports {pci_express_x16_txn[13]}]
set_property PACKAGE_PIN BA6 [get_ports {pci_express_x16_rxp[12]}]
set_property PACKAGE_PIN BA5 [get_ports {pci_express_x16_rxn[12]}]
set_property PACKAGE_PIN BA11 [get_ports {pci_express_x16_txp[12]}]
set_property PACKAGE_PIN BA10 [get_ports {pci_express_x16_txn[12]}]
# Clock
set_property PACKAGE_PIN AR14 [get_ports pcie_refclk_clk_n]
set_property PACKAGE_PIN AR15 [get_ports pcie_refclk_clk_p]

set_property PACKAGE_PIN AY4 [get_ports {pci_express_x16_rxp[11]}]
set_property PACKAGE_PIN AY3 [get_ports {pci_express_x16_rxn[11]}]
set_property PACKAGE_PIN AY9 [get_ports {pci_express_x16_txp[11]}]
set_property PACKAGE_PIN AY8 [get_ports {pci_express_x16_txn[11]}]
set_property PACKAGE_PIN AW2 [get_ports {pci_express_x16_rxp[10]}]
set_property PACKAGE_PIN AW1 [get_ports {pci_express_x16_rxn[10]}]
set_property PACKAGE_PIN AW11 [get_ports {pci_express_x16_txp[10]}]
set_property PACKAGE_PIN AW10 [get_ports {pci_express_x16_txn[10]}]
set_property PACKAGE_PIN AW6 [get_ports {pci_express_x16_rxp[9]}]
set_property PACKAGE_PIN AW5 [get_ports {pci_express_x16_rxn[9]}]
set_property PACKAGE_PIN AV9 [get_ports {pci_express_x16_txp[9]}]
set_property PACKAGE_PIN AV8 [get_ports {pci_express_x16_txn[9]}]
set_property PACKAGE_PIN AV4 [get_ports {pci_express_x16_rxp[8]}]
set_property PACKAGE_PIN AV3 [get_ports {pci_express_x16_rxn[8]}]
set_property PACKAGE_PIN AU7 [get_ports {pci_express_x16_txp[8]}]
set_property PACKAGE_PIN AU6 [get_ports {pci_express_x16_txn[8]}]
set_property PACKAGE_PIN AU2 [get_ports {pci_express_x16_rxp[7]}]
set_property PACKAGE_PIN AU1 [get_ports {pci_express_x16_rxn[7]}]
set_property PACKAGE_PIN AU11 [get_ports {pci_express_x16_txp[7]}]
set_property PACKAGE_PIN AU10 [get_ports {pci_express_x16_txn[7]}]
set_property PACKAGE_PIN AT4 [get_ports {pci_express_x16_rxp[6]}]
set_property PACKAGE_PIN AT3 [get_ports {pci_express_x16_rxn[6]}]
set_property PACKAGE_PIN AT9 [get_ports {pci_express_x16_txp[6]}]
set_property PACKAGE_PIN AT8 [get_ports {pci_express_x16_txn[6]}]
set_property PACKAGE_PIN AR2 [get_ports {pci_express_x16_rxp[5]}]
set_property PACKAGE_PIN AR1 [get_ports {pci_express_x16_rxn[5]}]
set_property PACKAGE_PIN AR7 [get_ports {pci_express_x16_txp[5]}]
set_property PACKAGE_PIN AR6 [get_ports {pci_express_x16_txn[5]}]
set_property PACKAGE_PIN AP4 [get_ports {pci_express_x16_rxp[4]}]
set_property PACKAGE_PIN AP3 [get_ports {pci_express_x16_rxn[4]}]
set_property PACKAGE_PIN AR11 [get_ports {pci_express_x16_txp[4]}]
set_property PACKAGE_PIN AR10 [get_ports {pci_express_x16_txn[4]}]
#set_property PACKAGE_PIN AL14             [get_ports {pcie_clk0_n} ]                       ;# Bank 227 - MGTREFCLK0N_227
#set_property PACKAGE_PIN AL15             [get_ports {pcie_clk0_n} ]                       ;# Bank 227 - MGTREFCLK0P_227
#set_property PACKAGE_PIN AK12             [get_ports {sys_clk2_n} ]                        ;# Bank 227 - MGTREFCLK1N_227
#set_property PACKAGE_PIN AK13             [get_ports {sys_clk2_n} ]                        ;# Bank 227 - MGTREFCLK1P_227
set_property PACKAGE_PIN AN2 [get_ports {pci_express_x16_rxp[3]}]
set_property PACKAGE_PIN AN1 [get_ports {pci_express_x16_rxn[3]}]
set_property PACKAGE_PIN AP9 [get_ports {pci_express_x16_txp[3]}]
set_property PACKAGE_PIN AP8 [get_ports {pci_express_x16_txn[3]}]
set_property PACKAGE_PIN AN6 [get_ports {pci_express_x16_rxp[2]}]
set_property PACKAGE_PIN AN5 [get_ports {pci_express_x16_rxn[2]}]
set_property PACKAGE_PIN AN11 [get_ports {pci_express_x16_txp[2]}]
set_property PACKAGE_PIN AN10 [get_ports {pci_express_x16_txn[2]}]
set_property PACKAGE_PIN AM4 [get_ports {pci_express_x16_rxp[1]}]
set_property PACKAGE_PIN AM3 [get_ports {pci_express_x16_rxn[1]}]
set_property PACKAGE_PIN AM9 [get_ports {pci_express_x16_txp[1]}]
set_property PACKAGE_PIN AM8 [get_ports {pci_express_x16_txn[1]}]
set_property PACKAGE_PIN AL2 [get_ports {pci_express_x16_rxp[0]}]
set_property PACKAGE_PIN AL1 [get_ports {pci_express_x16_rxn[0]}]
set_property PACKAGE_PIN AL11 [get_ports {pci_express_x16_txp[0]}]
set_property PACKAGE_PIN AL10 [get_ports {pci_express_x16_txn[0]}]

create_clock -period 10.000 -name pcie_refclk [get_ports pcie_refclk_clk_p]




# 100MHz DDR0 System clock
set_property PACKAGE_PIN BJ43 [get_ports mc_clk_p]
set_property PACKAGE_PIN BJ44 [get_ports mc_clk_n]


# DDR4 RDIMM Controller 0, 72-bit Data Interface, x4 Componets, Single Rank
#     <<<NOTE>>> DQS Clock strobes have been swapped from JEDEC standard to match Xilinx MIG Clock order:
#                JEDEC Order   DQS ->  0  9  1 10  2 11  3 12  4 13  5 14  6 15  7 16  8 17
#                Xil MIG Order DQS ->  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17
#
set_property -dict {PACKAGE_PIN BH44 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[16]}]
set_property -dict {PACKAGE_PIN BL46 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[15]}]
#set_property -dict {PACKAGE_PIN BE46 IOSTANDARD SSTL12_DCI}              [ get_ports  {c0_ddr4_odt[1]} ]         ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_ODT1"    - IO_L22N_T3U_N7_DBC_AD0N_D05_65
#set_property -dict {PACKAGE_PIN BK44 IOSTANDARD SSTL12_DCI}              [ get_ports  {#NA} ]                    ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CS_B3"   - IO_L11N_T1U_N9_GC_A11_D27_65
set_property -dict {PACKAGE_PIN BK46 IOSTANDARD SSTL12_DCI} [get_ports {ddr_cs_n[0]}]
set_property -dict {PACKAGE_PIN BE44 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[13]}]
#set_property -dict {PACKAGE_PIN BL47 IOSTANDARD SSTL12_DCI}              [ get_ports  {ddr_addr[17]} ]           ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_ADR17"   - IO_L7P_T1L_N0_QBC_AD13P_A18_65
set_property -dict {PACKAGE_PIN BE43 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[14]}]
set_property -dict {PACKAGE_PIN BG44 IOSTANDARD SSTL12_DCI} [get_ports {ddr_odt[0]}]
#set_property -dict {PACKAGE_PIN BE45 IOSTANDARD SSTL12_DCI}              [ get_ports  {c0_ddr4_cs_n[1]} ]        ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CS_B1"   - IO_L22P_T3U_N6_DBC_AD0P_D04_65
#set_property -dict {PACKAGE_PIN BD42 IOSTANDARD SSTL12_DCI}              [ get_ports  {c0_ddr4_cs_n[2]} ]        ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CS_B2"   - IO_L23N_T3U_N9_PERSTN1_I2C_SDA_65
set_property -dict {PACKAGE_PIN BH45 IOSTANDARD SSTL12_DCI} [get_ports {ddr_ba[0]}]
set_property -dict {PACKAGE_PIN BG45 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[10]}]
set_property -dict {PACKAGE_PIN BJ46 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr_ck_n[0]}]
set_property -dict {PACKAGE_PIN BH46 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr_ck_p[0]}]
#set_property -dict {PACKAGE_PIN BK41 IOSTANDARD DIFF_SSTL12_DCI}         [ get_ports  {ddr_ck_n[1]} ]        ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CK_C1"   - IO_L15N_T2L_N5_AD11N_A03_D19_65
#set_property -dict {PACKAGE_PIN BJ41 IOSTANDARD DIFF_SSTL12_DCI}         [ get_ports  {ddr_ck_p[1]} ]        ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CK_T1"   - IO_L15P_T2L_N4_AD11P_A02_D18_65
set_property -dict {PACKAGE_PIN BM47 IOSTANDARD SSTL12_DCI} [get_ports {ddr_ba[1]}]
set_property -dict {PACKAGE_PIN BF45 IOSTANDARD SSTL12_DCI} [get_ports ddr_parity]
set_property -dict {PACKAGE_PIN BF46 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[0]}]
set_property -dict {PACKAGE_PIN BK45 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[2]}]
set_property -dict {PACKAGE_PIN BG43 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[1]}]
set_property -dict {PACKAGE_PIN BL45 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[4]}]
set_property -dict {PACKAGE_PIN BF42 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[3]}]
#set_property -dict {PACKAGE_PIN BC42 IOSTANDARD LVCMOS12}                [ get_ports  {c0_ddr4_alert_n} ]        ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_ALERT_B" - IO_L23P_T3U_N8_I2C_SCLK_65
set_property -dict {PACKAGE_PIN BK43 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[8]}]
set_property -dict {PACKAGE_PIN BL43 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[7]}]
set_property -dict {PACKAGE_PIN BD41 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[11]}]
set_property -dict {PACKAGE_PIN BM42 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[9]}]
set_property -dict {PACKAGE_PIN BF43 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[5]}]
set_property -dict {PACKAGE_PIN BG42 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[6]}]
#set_property -dict {PACKAGE_PIN BJ42 IOSTANDARD SSTL12_DCI}              [ get_ports  {c0_ddr4_cke[1]} ]         ;# Bank  65 VCCO - VCC1V2 Net "DDR4_C0_CKE1"    - IO_L13N_T2L_N1_GC_QBC_A07_D23_65
set_property -dict {PACKAGE_PIN BE41 IOSTANDARD SSTL12_DCI} [get_ports {ddr_bg[1]}]
set_property -dict {PACKAGE_PIN BL42 IOSTANDARD SSTL12_DCI} [get_ports {ddr_addr[12]}]
set_property -dict {PACKAGE_PIN BH41 IOSTANDARD SSTL12_DCI} [get_ports ddr_act_n]
set_property -dict {PACKAGE_PIN BH42 IOSTANDARD SSTL12_DCI} [get_ports {ddr_cke[0]}]
set_property -dict {PACKAGE_PIN BF41 IOSTANDARD SSTL12_DCI} [get_ports {ddr_bg[0]}]
set_property -dict {PACKAGE_PIN BE53 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[66]}]
set_property -dict {PACKAGE_PIN BE54 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[67]}]
set_property -dict {PACKAGE_PIN BJ54 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[16]}]
set_property -dict {PACKAGE_PIN BH54 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[16]}]
set_property -dict {PACKAGE_PIN BG54 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[64]}]
set_property -dict {PACKAGE_PIN BG53 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[65]}]
set_property -dict {PACKAGE_PIN BK53 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[71]}]
set_property -dict {PACKAGE_PIN BK54 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[70]}]
set_property -dict {PACKAGE_PIN BH52 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[68]}]
set_property -dict {PACKAGE_PIN BG52 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[69]}]
set_property -dict {PACKAGE_PIN BJ53 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[17]}]
set_property -dict {PACKAGE_PIN BJ52 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[17]}]
set_property -dict {PACKAGE_PIN BL52 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[34]}]
set_property -dict {PACKAGE_PIN BL51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[35]}]
set_property -dict {PACKAGE_PIN BM50 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[8]}]
set_property -dict {PACKAGE_PIN BM49 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[8]}]
#set_property -dict {PACKAGE_PIN BK29 IOSTANDARD LVCMOS12}                [ get_ports  {c0_ddr4_event_n} ]        ;# Bank  64 VCCO - VCC1V2 Net "DDR4_C0_EVENT_B" - IO_T3U_N12_64
set_property -dict {PACKAGE_PIN BL53 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[33]}]
set_property -dict {PACKAGE_PIN BM52 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[32]}]
set_property -dict {PACKAGE_PIN BN49 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[38]}]
set_property -dict {PACKAGE_PIN BM48 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[39]}]
set_property -dict {PACKAGE_PIN BN51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[37]}]
set_property -dict {PACKAGE_PIN BN50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[36]}]
set_property -dict {PACKAGE_PIN BP49 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[9]}]
set_property -dict {PACKAGE_PIN BP48 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[9]}]
set_property -dict {PACKAGE_PIN BH35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[25]}]
set_property -dict {PACKAGE_PIN BH34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[24]}]
set_property -dict {PACKAGE_PIN BK35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[6]}]
set_property -dict {PACKAGE_PIN BK34 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[6]}]
set_property -dict {PACKAGE_PIN BG33 IOSTANDARD LVCMOS12} [get_ports ddr_reset_n]
set_property -dict {PACKAGE_PIN BF36 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[27]}]
set_property -dict {PACKAGE_PIN BF35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[26]}]
set_property -dict {PACKAGE_PIN BJ34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[29]}]
set_property -dict {PACKAGE_PIN BJ33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[28]}]
set_property -dict {PACKAGE_PIN BG34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[30]}]
set_property -dict {PACKAGE_PIN BG35 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[31]}]
set_property -dict {PACKAGE_PIN BJ32 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[7]}]
set_property -dict {PACKAGE_PIN BH32 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[7]}]
set_property -dict {PACKAGE_PIN BL31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[17]}]
set_property -dict {PACKAGE_PIN BK31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[16]}]
set_property -dict {PACKAGE_PIN BM35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[4]}]
set_property -dict {PACKAGE_PIN BL35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[4]}]
set_property -dict {PACKAGE_PIN BL33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[19]}]
set_property -dict {PACKAGE_PIN BK33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[18]}]
set_property -dict {PACKAGE_PIN BM33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[21]}]
set_property -dict {PACKAGE_PIN BL32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[20]}]
set_property -dict {PACKAGE_PIN BP34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[23]}]
set_property -dict {PACKAGE_PIN BN34 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[22]}]
set_property -dict {PACKAGE_PIN BN35 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[5]}]
set_property -dict {PACKAGE_PIN BM34 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[5]}]
set_property -dict {PACKAGE_PIN BM44 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[58]}]
set_property -dict {PACKAGE_PIN BN45 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[57]}]
set_property -dict {PACKAGE_PIN BP46 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[14]}]
set_property -dict {PACKAGE_PIN BN46 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[14]}]
set_property -dict {PACKAGE_PIN BM45 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[59]}]
set_property -dict {PACKAGE_PIN BN44 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[56]}]
set_property -dict {PACKAGE_PIN BP44 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[61]}]
set_property -dict {PACKAGE_PIN BP43 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[60]}]
set_property -dict {PACKAGE_PIN BP47 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[63]}]
set_property -dict {PACKAGE_PIN BN47 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[62]}]
set_property -dict {PACKAGE_PIN BP42 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[15]}]
set_property -dict {PACKAGE_PIN BN42 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[15]}]
set_property -dict {PACKAGE_PIN BE50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[40]}]
set_property -dict {PACKAGE_PIN BE49 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[41]}]
set_property -dict {PACKAGE_PIN BF48 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[10]}]
set_property -dict {PACKAGE_PIN BF47 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[10]}]
set_property -dict {PACKAGE_PIN BE51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[42]}]
set_property -dict {PACKAGE_PIN BD51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[43]}]
set_property -dict {PACKAGE_PIN BF50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[47]}]
set_property -dict {PACKAGE_PIN BG50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[46]}]
set_property -dict {PACKAGE_PIN BF52 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[44]}]
set_property -dict {PACKAGE_PIN BF51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[45]}]
set_property -dict {PACKAGE_PIN BG49 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[11]}]
set_property -dict {PACKAGE_PIN BG48 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[11]}]
set_property -dict {PACKAGE_PIN BJ51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[49]}]
set_property -dict {PACKAGE_PIN BH51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[50]}]
set_property -dict {PACKAGE_PIN BJ47 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[12]}]
set_property -dict {PACKAGE_PIN BH47 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[12]}]
set_property -dict {PACKAGE_PIN BH50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[48]}]
set_property -dict {PACKAGE_PIN BH49 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[51]}]
set_property -dict {PACKAGE_PIN BK50 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[52]}]
set_property -dict {PACKAGE_PIN BJ48 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[55]}]
set_property -dict {PACKAGE_PIN BK51 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[53]}]
set_property -dict {PACKAGE_PIN BJ49 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[54]}]
set_property -dict {PACKAGE_PIN BK49 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[13]}]
set_property -dict {PACKAGE_PIN BK48 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[13]}]
set_property -dict {PACKAGE_PIN BL30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[2]}]
set_property -dict {PACKAGE_PIN BM30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[3]}]
set_property -dict {PACKAGE_PIN BN30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[0]}]
set_property -dict {PACKAGE_PIN BN29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[0]}]
set_property -dict {PACKAGE_PIN BP32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[1]}]
set_property -dict {PACKAGE_PIN BN32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[0]}]
set_property -dict {PACKAGE_PIN BP31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[6]}]
set_property -dict {PACKAGE_PIN BN31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[7]}]
set_property -dict {PACKAGE_PIN BP29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[4]}]
set_property -dict {PACKAGE_PIN BP28 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[5]}]
set_property -dict {PACKAGE_PIN BM29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[1]}]
set_property -dict {PACKAGE_PIN BM28 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[1]}]
set_property -dict {PACKAGE_PIN BH31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[9]}]
set_property -dict {PACKAGE_PIN BJ31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[8]}]
set_property -dict {PACKAGE_PIN BK30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[2]}]
set_property -dict {PACKAGE_PIN BJ29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[2]}]
set_property -dict {PACKAGE_PIN BF32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[10]}]
set_property -dict {PACKAGE_PIN BF33 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[11]}]
set_property -dict {PACKAGE_PIN BH29 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[12]}]
set_property -dict {PACKAGE_PIN BH30 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[13]}]
set_property -dict {PACKAGE_PIN BF31 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[14]}]
set_property -dict {PACKAGE_PIN BG32 IOSTANDARD POD12_DCI} [get_ports {ddr_dq[15]}]
set_property -dict {PACKAGE_PIN BG30 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_n[3]}]
set_property -dict {PACKAGE_PIN BG29 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr_dqs_p[3]}]

set_property -dict {PACKAGE_PIN D32 IOSTANDARD LVCMOS18} [get_ports hbm_cattrip]
set_property PULLDOWN true [get_ports hbm_cattrip]

set_false_path -from [get_pins chipset/chipset_impl/u280_polara_i/polara_i/ddr4_0/inst/u_ddr4_mem_intfc/u_ddr_cal_top/*/C] -to [get_pins chipset/chipset_impl/init_calib_complete_f_reg/D]

set_property USER_SLR_ASSIGNMENT SLR0 [get_cells [get_cells -of_objects [get_nets -of_objects [get_pins -hierarchical qdma_0/axi_aclk]]]]



